### ISSUE TITLE
codo-admin启动报错

### ISSUE THREAD

**Issue by luobo911** [opendevops-cn/codo-admin#19]
codo-admin启动后，报错，进入容器后访问容器内部9800，9801，9802端口，都提示如下错误

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1676, in _execute
    result = self.prepare()
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 2431, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found

不知道如何解决

**Comment by czxin788** [comment]
我也遇到这个错误，不知道如何解决
