### ISSUE TITLE
login failed ,how to  resolve

### ISSUE THREAD

**Issue by cmyk343** [opendevops-cn/codo-admin#25]
2020-12-15 19:50 +08:00: [E 201215 19:50:58 web:1793] Uncaught exception POST /login/ (127.0.0.1)
2020-12-15 19:50 +08:00:     HTTPServerRequest(protocol='http', host='mg.opendevops.cn', method='POST', uri='/login/', version='HTTP/1.0', remote_ip='127.0.0.1')
2020-12-15 19:50 +08:00:     Traceback (most recent call last):
2020-12-15 19:50 +08:00:       File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 1702, in _execute
2020-12-15 19:50 +08:00:         result = method(*self.path_args, **self.path_kwargs)
2020-12-15 19:50 +08:00:       File "/opt/codo/codo-admin/mg/handlers/login_handler.py", line 138, in post
2020-12-15 19:50 +08:00:         self.set_cookie('auth_key', auth_key, expires_days=1)
2020-12-15 19:50 +08:00:       File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 622, in set_cookie
2020-12-15 19:50 +08:00:         value = escape.native_str(value)
2020-12-15 19:50 +08:00:       File "/usr/local/lib64/python3.6/site-packages/tornado/escape.py", line 228, in to_unicode
2020-12-15 19:50 +08:00:         raise TypeError("Expected bytes, unicode, or None; got %r" % type(value))
2020-12-15 19:50 +08:00:     TypeError: Expected bytes, unicode, or None; got <class 'AttributeError'>

**Comment by cmyk343** [comment]
重装opsdk就可以了，非bug

**Comment by haiya512** [comment]
我的情况是这样的，服务器访问github大部分时候访问不了，得尝试很多次才行，看RP，
所以我就直接浏览器打包下载，然后上传到了服务器上，运行python setup.py install ，继续下去的时候就报错，然后手动删除site-packages 目录下的opssdk，再用官网文档的方式去安装，就没问题了

不过遇到了新的问题，codo-task报错了
```
2021-08-13 16:16 +08:00: SyntaxError: invalid syntax
2021-08-13 16:16 +08:00: Traceback (most recent call last):
2021-08-13 16:16 +08:00:   File "startup.py", line 13, in <module>
2021-08-13 16:16 +08:00:     from biz.applications import Application as TaskApp
2021-08-13 16:16 +08:00:   File "/opt/codo/codo-task/biz/applications.py", line 12, in <module>
2021-08-13 16:16 +08:00:     from biz.handlers.task_accept import accept_task_urls
2021-08-13 16:16 +08:00:   File "/opt/codo/codo-task/biz/handlers/task_accept.py", line 12, in <module>
2021-08-13 16:16 +08:00:     from websdk.mqhelper import MessageQueueBase
2021-08-13 16:16 +08:00:   File "/opt/venv/lib/python3.7/site-packages/websdk/mqhelper.py", line 9, in <module>
2021-08-13 16:16 +08:00:     import pika
2021-08-13 16:16 +08:00:   File "/opt/venv/lib/python3.7/site-packages/pika/__init__.py", line 20, in <module>
2021-08-13 16:16 +08:00:     from pika.adapters import BaseConnection
2021-08-13 16:16 +08:00:   File "/opt/venv/lib/python3.7/site-packages/pika/adapters/__init__.py", line 43, in <module>
2021-08-13 16:16 +08:00:     from pika.adapters.libev_connection import LibevConnection
2021-08-13 16:16 +08:00:   File "/opt/venv/lib/python3.7/site-packages/pika/adapters/libev_connection.py", line 106
2021-08-13 16:16 +08:00:     self.async = None
2021-08-13 16:16 +08:00:              ^
2021-08-13 16:16 +08:00: SyntaxError: invalid syntax
```
